import { mkdir, writeFile } from 'node:fs/promises'

// Pinned artwork and attribution; the application never fetches icons at runtime.
const revision = '777807a262bb7384ff406fd4b35fdcd02e9514c3'
const base = `https://raw.githubusercontent.com/simple-icons/simple-icons/${revision}`
const selected = {
  npm: 'npm',
  pnpm: 'pnpm',
  yarn: 'Yarn',
  bun: 'Bun',
  gradle: 'Gradle',
  python: 'Python',
  rust: 'Rust',
  go: 'Go',
  docker: 'Docker',
  apachemaven: 'Apache Maven',
  uv: 'uv',
  nodedotjs: 'Node.js',
  task: 'Task',
}
async function get(file) {
  const response = await fetch(`${base}/${file}`)
  if (!response.ok) throw new Error(`${file}: ${response.status}`)
  return response.text()
}
const data = JSON.parse(await get('data/simple-icons.json'))
const icons = Array.isArray(data) ? data : data.icons
const paths = {},
  sources = []
for (const [slug, title] of Object.entries(selected)) {
  const entry = icons.find((icon) => icon.title === title)
  if (!entry) throw new Error(`Missing attribution for ${title}`)
  const svg = await get(`icons/${slug}.svg`)
  const d = svg.match(/<path d="([^"]+)"/u)?.[1]
  if (!d || !/^[MmZzLlHhVvCcSsQqTtAa0-9.,eE+\s-]+$/u.test(d))
    throw new Error(`Unexpected SVG path for ${slug}`)
  paths[slug] = d
  sources.push({ slug, ...entry, artwork: `${base}/icons/${slug}.svg` })
}
const notices = 'public/third-party/task-icons'
await mkdir(notices, { recursive: true })
await writeFile(
  'app/assets/tool-icon-paths.ts',
  `// Generated by scripts/task-icons.mjs. Attribution: public/third-party/task-icons/README.md.\n` +
    `export const toolIconPaths = ${JSON.stringify(paths, null, 2)} as const\n`,
)
await writeFile(
  `${notices}/sources.json`,
  JSON.stringify({ revision, icons: sources }, null, 2) + '\n',
)
await writeFile(`${notices}/SIMPLE-ICONS-LICENSE.txt`, await get('LICENSE.md'))
await writeFile(`${notices}/SIMPLE-ICONS-DISCLAIMER.md`, await get('DISCLAIMER.md'))
const apacheLicense = await fetch('https://www.apache.org/licenses/LICENSE-2.0.txt')
if (!apacheLicense.ok) throw new Error(`Apache license: ${apacheLicense.status}`)
await writeFile(`${notices}/APACHE-2.0.txt`, await apacheLicense.text())
console.log(`Saved ${sources.length} tool icons and their source metadata.`)
